# Análisis de datos

### Librerias utilizadas

In [1]:
import pandas as pd
#pip install pandas-profiling
import pandas_profiling

### Archivo csv utilizado

In [2]:
csvfile = pd.read_csv('E:\Maestria\hurtopersona.csv',delimiter=';',error_bad_lines=False,low_memory=False)

### Muestra de archivo csv

In [3]:
csvfile.head()

,seguridad.fecha_hecho,seguridad.cantidad,seguridad.latitud,seguridad.longitud,seguridad.sexo,seguridad.edad,seguridad.estado_civil,seguridad.grupo_actor,seguridad.actividad_delictiva,seguridad.parentesco,...,seguridad.codigo_comuna,seguridad.lugar,seguridad.sede_receptora,seguridad.bien,seguridad.categoria_bien,seguridad.grupo_bien,seguridad.modelo,seguridad.color,seguridad.permiso,seguridad.unidad_medida
0,2017-01-01 01:00:00,1.0,6.299703,-75.582016,Mujer,33,Unión marital de hecho,Sin dato,Sin dato,Sin dato,...,6,Vía pública,Doce de Octubre,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato
1,2017-01-01 15:00:00,1.0,6.250917,-75.566160,Mujer,26,Soltero(a),Sin dato,Sin dato,Sin dato,...,10,Vía pública,Candelaria,Celular,Tecnología,Mercancía,-1,Sin dato,Sin dato,Sin dato
2,2017-01-01 14:00:00,1.0,6.274836,-75.554909,Hombre,30,Soltero(a),Sin dato,Sin dato,Sin dato,...,4,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato
3,2017-01-01 16:00:00,1.0,6.276236,-75.553533,Hombre,37,Casado(a),Sin dato,Sin dato,Sin dato,...,4,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,-1,Negro,Sin dato,Sin dato
4,2017-01-01 16:00:00,1.0,6.250339,-75.586914,Hombre,87,Casado(a),Sin dato,Sin dato,Sin dato,...,11,Vía pública,Laureles,Billetera,Prendas de vestir y accesorios,Mercancía,-1,Sin dato,Sin dato,Sin dato

### Descripción basica de los datos

In [4]:
csvfile.describe()

,seguridad.cantidad,seguridad.latitud,seguridad.longitud,seguridad.edad,seguridad.modelo
count,215279.0,201048.000000,201048.000000,215279.000000,215279.000000
mean,1.0,6.246808,-75.574119,34.295342,0.209226
std,0.0,0.040884,0.478444,13.077355,49.193936
min,1.0,3.855871,-76.317445,-1.000000,-1.000000
25%,1.0,6.234691,-75.587059,25.000000,-1.000000
50%,1.0,6.249058,-75.571806,32.000000,-1.000000
75%,1.0,6.258849,-75.566160,42.000000,-1.000000
max,1.0,10.155289,75.607180,96.000000,2015.000000

### Análisis de datos utilizando pandas_profiling

In [ ]:
pandas_profiling.ProfileReport(csvfile)

# Limpieza de datos

## Eliminacion de columnas

In [5]:
csvfile.drop(['seguridad.grupo_actor','seguridad.estado_civil','seguridad.actividad_delictiva','seguridad.parentesco','seguridad.ocupacion','seguridad.discapacidad','seguridad.grupo_especial','seguridad.nivel_academico','seguridad.testigo','seguridad.conducta','seguridad.caracterizacion','seguridad.articulo_penal','seguridad.categoria_penal','seguridad.modelo','seguridad.color','seguridad.permiso','seguridad.unidad_medida'], inplace=True, axis=1)

# Extraccion de datos de la fecha

In [6]:
csvfile['anio'] = pd.DatetimeIndex(csvfile['seguridad.fecha_hecho']).year
csvfile['mes'] = pd.DatetimeIndex(csvfile['seguridad.fecha_hecho']).month
csvfile['dia'] = pd.DatetimeIndex(csvfile['seguridad.fecha_hecho']).day
csvfile['hora'] = pd.DatetimeIndex(csvfile['seguridad.fecha_hecho']).hour
csvfile['dia_semana'] = pd.DatetimeIndex(csvfile['seguridad.fecha_hecho']).dayofweek

csvfile.head()

#csvfile.to_csv(r'E:\Maestria\prueba.csv', index = False)

,seguridad.fecha_hecho,seguridad.cantidad,seguridad.latitud,seguridad.longitud,seguridad.sexo,seguridad.edad,seguridad.medio_transporte,seguridad.modalidad,seguridad.conducta_especial,seguridad.arma_medio,...,seguridad.lugar,seguridad.sede_receptora,seguridad.bien,seguridad.categoria_bien,seguridad.grupo_bien,anio,mes,dia,hora,dia_semana
0,2017-01-01 01:00:00,1.0,6.299703,-75.582016,Mujer,33,Caminata,Atraco,De celular,Arma cortopunzante,...,Vía pública,Doce de Octubre,Celular,Tecnología,Mercancía,2017,1,1,1,6
1,2017-01-01 15:00:00,1.0,6.250917,-75.566160,Mujer,26,Caminata,Atraco,Sin dato,Arma cortopunzante,...,Vía pública,Candelaria,Celular,Tecnología,Mercancía,2017,1,1,15,6
2,2017-01-01 14:00:00,1.0,6.274836,-75.554909,Hombre,30,Caminata,Descuido,De celular,No,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,2017,1,1,14,6
3,2017-01-01 16:00:00,1.0,6.276236,-75.553533,Hombre,37,Taxi,Atraco,De celular,Arma de fuego,...,Vía pública,Aranjuez,Celular,Tecnología,Mercancía,2017,1,1,16,6
4,2017-01-01 16:00:00,1.0,6.250339,-75.586914,Hombre,87,Caminata,Engaño,Sin dato,No,...,Vía pública,Laureles,Billetera,Prendas de vestir y accesorios,Mercancía,2017,1,1,16,6